import type NetlifyCmsField from '../../../interfaces/NetlifyCmsField'

export default <NetlifyCmsField>{
  label: 'Dual text',
  name: 'dual-text',
  widget: 'object',
  summary: 'Dual text | {{fields.leftText.title}} & {{fields.rightText.title}}',
  fields: [
    {
      label: 'Left text',
      name: 'leftText',
      widget: 'object',
      summary: 'Left text | {{fields.title}}',
      fields: [
        {
          label: 'Title',
          name: 'title',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text',
          name: 'text',
          widget: 'markdown',
          required: true,
          buttons: [
            'bold',
            'italic',
            // 'code',
            'link',
            // 'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            // 'quote',
            'bulleted-list',
            'numbered-list',
          ],
          editor_components: [],
          modes: ['rich_text'],
        },
      ],
    },
    {
      label: 'Right text',
      name: 'rightText',
      widget: 'object',
      summary: 'Right text | {{fields.title}}',
      fields: [
        {
          label: 'Title',
          name: 'title',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text',
          name: 'text',
          widget: 'markdown',
          required: true,
          buttons: [
            'bold',
            'italic',
            // 'code',
            'link',
            // 'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            // 'quote',
            'bulleted-list',
            'numbered-list',
          ],
          editor_components: [],
          modes: ['rich_text'],
        },
      ],
    },
    {
      label: 'Component',
      name: 'component',
      widget: 'hidden',
      default: 'dual-text',
    },
  ],
}
